### ISSUE TITLE
Files not Downloading correctly

### ISSUE THREAD

**Issue by SaintLamp** [Dontwait00/nXDownload#17]
recently I have been attempting to download the latest goldleaf.nsp from here https://github.com/XorTroll/Goldleaf/releases/download/0.5/Goldleaf.nsp
the nsp was experiencing install issues this lead me to check the file on my PC and I discovered the downloaded file on my switch was much smaller then it should be, on repeated downloads of the same file through different file hosts the .nsp files size changed wildly from as small a 9 bytes to 600 bytes

**Comment by SegFault42** [comment]
See issue #14

**Comment by SaintLamp** [comment]
I also tried different file hosts included but not limited to mediafire
