### ISSUE TITLE
More Link

### ISSUE THREAD

**Issue by BexDevs** [Dontwait00/nXDownload#2]
Hi, i have 180 link on my input.txt... when I download a game from it, switch are crashing.
Can you help me?

**Comment by 0d3n3h547v** [comment]
Can you please give me informations about:
1. what version of nXDownload are you using? 
2. What website are you going to?
3. What type of link are you giving?
4. What extension is the file?

**Comment by BexDevs** [comment]
I'm use 0.9 last versions
Website is my personal vps
Link is: http://192.168.1.1 (it's example)
Nsp file

**Comment by 0d3n3h547v** [comment]
Oh i see. `libcurl` doesnt support localhost. the best option for you is a FTP protocol. But my tool doesnt sopported it still. In the next releases i will support FTP, if thats requested.
Meanwhile, while you cant use localhost, you can look for 1fichier.com & Mediafire.com links. The work pretty well.

Thanks for your attention.

**Comment by BexDevs** [comment]
Oh ok... when you release ftp connection update?

**Comment by 0d3n3h547v** [comment]
Soon:tm:

The source code right now needs to be to be parsed better.
And right now, im doing so for `enhance more stability & to improve user experience` in terms of `portability`

**Comment by BexDevs** [comment]
Ok. I'm wait it

**Comment by BexDevs** [comment]
Hi bro. Can i use Gdrive for download?

**Comment by 0d3n3h547v** [comment]
Yeah for sure! Its better if you compress the url first, for doing better

**Comment by BexDevs** [comment]
Compress url? Short url?

**Comment by 0d3n3h547v** [comment]
Yeah, thats right.
