### ISSUE TITLE
Crash if enter twice in download menu

### ISSUE THREAD

**Issue by SegFault42** [Dontwait00/nXDownload#4]
Console crash if i download update or file 2 times.

Try to update nXDownload then push [-] and redownload the update.

**Comment by 0d3n3h547v** [comment]
Yeah i have already noticed this malfunction. The problem that is cousing this behavior, is `curl_setopt_cleanup()` [for example here](https://github.com/Dontwait00/nXDownload/blob/alpha/source/download.c#L420) which *in theory* should reset structures like `CURLCode` and `CURL` from [download.h](https://github.com/Dontwait00/nXDownload/blob/alpha/source/includes/download.h#L17)

Going to try and fix it.

**Comment by SegFault42** [comment]
ok will see that

**Comment by 0d3n3h547v** [comment]
Fixed after commit [a839377](https://github.com/Dontwait00/nXDownload/commit/a839377fa4146d883115bfc70f14a37aedfaa0c9)
