### ISSUE TITLE
tmpfile.txt ??

### ISSUE THREAD

**Issue by SegFault42** [Dontwait00/nXDownload#6]
In FILE_TRANSFER_HTTP_TEMPORALY you create tmpfile.txt and you read it in FILE_TRANSFER_HTTP. After the download you need the file or you can remove it ?

**Comment by 0d3n3h547v** [comment]
Originally it was designed to pass arguments through function to function, meanwhile, i was going to push a new commit adding the possibilty to use the 'tmpfile.txt' (which should contain the link) if exists. Otherwhise i thought that would have be gone to far if passing the argument over `menu_main()` and then to `FILE_TRANSFER_HTTP()`. What you think about it? Should i change behavior between functions?

**Comment by SegFault42** [comment]
thank you, i will see that after.

**Comment by 0d3n3h547v** [comment]
> Originally it was designed to pass arguments through function to function, meanwhile, i was going to push a new commit adding the possibilty to use the 'tmpfile.txt' (which should contain the link) if exists. Otherwhise i thought that would have be gone to far if passing the argument over `menu_main()` and then to `FILE_TRANSFER_HTTP()`. What you think about it? Should i change behavior between functions?

i just noticed that there was already implemented to re-use `tmpfile.txt`. Btw, yes you should be fine if you delete it.

**Comment by 0d3n3h547v** [comment]
Okay, i decided to close this issue, as isnt really a issue. Btw, i founded the unknown crash, and have already fixed it, but seems to be broken `helper.c`. Once risolved, i will pubblicate the fixes. I hope this should be the last fixes and ready to push `v1.0b`

**Comment by SegFault42** [comment]
ok. Do you have discord ? 
if you have, add me : 0xDEADBEEF#4536

**Comment by skylar2k** [comment]
00 ıllıllı ď๏ɲţώąɨţ ıllıllı#7745
or his discord server
https://discord.gg/qN4q5s

**Comment by SegFault42** [comment]
thank you
